---
user: ubuntu
group: ubuntu
home: "/home/{{ user }}"
java_home: /usr

venv_dir: "{{ home }}/venv"
netdata_dir: /opt/netdata

# Python version (should be overridden by main vars.yml)
python_version: 3.10

java_pkgs:
        - software-properties-common
        - ca-certificates
        - openjdk-11-jre-headless
        - openjdk-11-jdk-headless

nfs_pkgs:
        - nfs-kernel-server
        - nfs-common
        - cryptsetup

python_pkgs:
        - python{{ python_version }}
        - python{{ python_version }}-venv
        - python3-pip
        - python3-passlib

netdata_version: v1.23.2
netdata_pkgs: 
        - zlib1g-dev
        - uuid-dev
        - libuv1-dev
        - liblz4-dev
        - libjudy-dev
        - libssl-dev
        - libmnl-dev
        - gcc
        - make
        - git
        - autoconf
        - autoconf-archive
        - autogen
        - automake
        - pkg-config
        - curl
        - python3
        - cmake

nginx_pkgs:
        - zlib1g-dev
        - libpcre3
        - libpcre3-dev
        - libssl-dev

nginx_version: nginx-1.24.0
nginx_tarball_url: "http://nginx.org/download/{{ nginx_version }}.tar.gz"
nginx_install_dir: "/tmp/{{ nginx_version }}"
nginx_prefix: "/etc/nginx"
nginx_custom_modules: "--with-http_auth_request_module --with-http_sub_module --with-http_ssl_module"
subs_filter_path: "/tmp/ngx_http_substitutions_filter_module"
