---
hadoop_version: 3.3.6 # TODO: Merge with the main vars.yaml
hadoop_mirror: https://mirrors.sonic.net/mirrors/apache/hadoop/common

# Cache for pre-staged artifacts (S3-compatible, path-style). Override if needed.
# cache_base_url: https://cog.sanger.ac.uk/osdataproc-cache

hadoop_download_dir: /opt/osdataproc
hadoop_install_dir: /opt/hadoop

hadoop_home: "{{ hadoop_install_dir }}"
hadoop_user: "{{ user }}"
hadoop_group: "{{ group }}"
hadoop_logs_dir: "{{ hadoop_home }}/logs"
hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"

hdfs_home: /opt/hdfs
hdfs_replicas: 1
hdfs_namenode_dir: "{{ hdfs_home }}/namenode"
hdfs_datanode_dir: "{{ hdfs_home }}/datanode"

yarn_home: /opt/yarn
yarn_logs_dir: "{{ yarn_home }}/logs"

aws_java_sdk_version: 1.11.375 # check https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/{{ hadoop_version }}

# Slack/email netdata notification settings (email client must be configured)
netdata_slack_webhook: ""
netdata_email: ""
