---
spark_version: 3.5.3 # TODO: Merge with the main vars.yaml
spark_mirror: https://archive.apache.org/dist/spark

# Cache for pre-staged artifacts (S3-compatible, path-style). Override if needed.
# cache_base_url: https://cog.sanger.ac.uk/osdataproc-cache

spark_download_dir: /opt/osdataproc
spark_install_dir: /opt/spark
spark_conf_dir: "{{ spark_install_dir }}/conf"

spark_home: "{{ spark_install_dir }}"
spark_user: "{{ user }}"
spark_group: "{{ group }}"

spark_master_host: spark-master
spark_master_port: 7077

hail_version: 0.2.133  # TODO: Merge with the main vars.yaml
hail_install_dir: "{{ venv_dir }}"
hail_home: "{{ hail_install_dir }}"

password: "{{ lookup('env', 'PASSWORD') }}"
