---

- hosts: spark_master
  become: true
  gather_facts: no
  tasks:
          - name: Wait max 600 seconds for target connection to become usable
            wait_for_connection:

          - include_role:
                  name: spark_master

- hosts: spark_workers,localhost
  become: true
  gather_facts: no
  tasks:
          - name: Wait max 600 seconds for target connection to become usable
            wait_for_connection:

          - include_role:
                  name: spark_workers